---
title: "ialeUK 25 Years of Conferences"
author: "James Millington"
date: "30 May 2019"
site: "bookdown::bookdown_site"
output:
  bookdown::gitbook: default
documentclass: book
link-citations: yes
---

# Overview and Summary

This is a collection of analyses of conference abstracts from 25 years of ialeUK conferences. Analysis is ongoing.  

A summary of initial observations is shown below. 

Use the table of contents (e.g. in the panel on the left) to navigate to detailed analysis (currently line and bar charts).  

*Suggestions for additional analysis*
- For some themes, categories for 'undefined' abstracts have sometimes been removed from analysis; need to provide information on how removing these 'undefined' studies includences the number of abstracts in the analysis. 
- Other suggestions for quant analyses welcome


[add links below later to specific sections]

## Summary: Abstracts though time

- General increase through time to early 2000s then drop but steady through 2010s
- NGO attendance has replaced declines in Government? (could check sum of Gov + NGO through time)
- Empirical studies have decreased through time while GIS and qualitative have increased through time
- Global studies only appear from 2014 onwards

## Summary: Author affiliation

- Academic contributors dominate, followed by Government (but as shown above, Government contributions have decreased recently, replaced by NGOs)
- Business contributors have noticeably lower proportion of empirical studies (expensive?) than other author types, substituted by GIS and qualitative
- Government and NGOs have greater proportion of Management and Conservation than Academic

## Summary: Landscape Type

- Lowland rural landscape studies dominate, followed by 'undefined' and Upland rural
- Seascape studies have largest proportion of qualitative methods
- Urban landscape studies are dominated by Local scale analysis
- Upland rural have larger proportion of national studies than Lowland rural
- Unsurprisingly, Green Infrastructure has greatest proportion in Urban landscapes and catchment-based approaches in Riverscapes
- Little study of cultural landscapes in Urban areas


## Summary: Organism

- Amphibians, Fish, Reptiles are little studied
- Plants have greatest proportions of longer studies (Decadal and Centuries) while Inverts have greatest proportion of shorter studies (Annual and Monthly) - makes sense given rates of change and life history of these organisms? 
- Businesses and private individuals largely study humans (based on proportional data)
- By absolute numbers NGOs dominate study of birds 
- Humans dominated by qualitative studies, with few empirical (i.e. few interviews, questionnaires?)
- Possibly surprisingly, plants do not have many RS studies
- Inverts dominated by 'mini' spatial extent studies

## Summary: Methods

- Empirical and Quantitative studies dominate with relatively little remote sensing
- Quantitative studies used relatively consistently across all landscape types
- Qualitative studies most commonly study humans (socio-economic dimensions and cultural landscapes)
- Theoretical studies have largely undefined extent and most commonly in not defining a landscape type
- Surprisingly few theoretical studies of scale and scaling?
- Relatively few empirical studies of ecosystem services

## Summary: Spatial Extent

- Dominated by Local extent studies, but also many at national and regional extents
- Global and Continental (largest extent) have fewest studies (8 and 27 respectively)
- Global extent studies are qualitatively different to other extent for several factors:
    + Global extent studies do not consider Lowland rural landscapes
    + Global extent studies do not consider amphibiams, birds, reptiles, or woodlands but have the largest proportions of Fish and generic Habitat studies
    + Global extent studies consider only Decades and Years timescales
- Smallest extents (micro and mini) have smallest proportions of Socio-Economic Dimensions studies but largest proportions of Biodiversity studies
- Consistent proportions of Management and Conservation studies across all extents
- Global, Continental and Undefined Extent have the greatest proportions of Theoretical,  Qualitative and Remote Sensing studies, whereas the smallest extents (mini and micro) have the largest proportions of Empirical studies (and Local have largest absolute number)

## Summary: Temporal Duration

- Majority of studies do not define or report their temporal duration (65%) (so not much point examining further?)
- Those that do generally have durations longer than Years (~89%) 

## Summary: Concepts

- Connectivity & fragmentation, LUCC and spatial analysis & modelling most frequent (composing > 50%) 
- Ecosystem services have greatest proportion of urban landscapes and lowest in lowland rural
- Connectivity & Fragmentation have greatest proportion of studies in Lowland rural landscapes and largest proportion of local studies
- Ecosystem services has smallest proportion of Empirical studies, largest proportion of global studies and fewest mini and micro studies

## Summary: Other Concepts

- Management & Conservation and Biodiversity studies componse the majority of studies (56%)
- Invasive pests have smallest number of studies (and therefore qualitative differences in proportions shown should be treated with caution)
- Management & Conservation studies have relatively low propotion of human studies; greatest proportion of Woodland studies
- Biodiversity studies have relatively large proportion of Inverts (along with invasives)
- Other than invasives, Biodiversity and Management & Conservation have greatest proportions of Empirical and lowest proportions of Theoretical
- Biodiversity and Management & Conservation have similar proportions; both with relatively large proportions of connectivity and fragmentation
